---
title: "Lab4_Bumblebee"
author: "Rachael Robinson, William Brickowski, Manasi Raol, Brady Kiesling"
date: "2/6/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Lab 4

## Team Questions:
  * Does smoking lead to babies born prematurely?
  * Does smoking lead to low birth weight? 

## Why are these questions important?
Reason: These questions are important because health behaviors during pregnancy are often a topic of interest. Determining what behaviors are more or less likely to result in healthy babies is important because it can inform women and families to improve health outcomes. Smoking in particular is an important question of interest due to the number of smokers during the 1960s, in which this data was collected.
  * This reason is important because it has wide-reaching impacts on generational health. Widespread habits can result in health affects on entire populations of babies, which could lead to consequences as this population of babies grows into adulthood. Trends in low birth weights or premature births could eventually impact the quality of life, labor, and health of larger populations.

## Team Plots:

### Question 1

### Question 2

## Conclusions:
  * Answer to first question
  * Answer to second question
  
## Recommendations:

### Recommendation for Q1

### Recommendation for Q2

## Preliminary Team Questions:
  * Which variables are similar between smokers and nonsmokers? Which are different?
  
## Team Plots for Prelimary Questions:


## Conclusions for Prelimary Questions:

## Individual Plots

### William

### Brady

### Manasi

### Rachael


## Individual contribution and non-defaults for plot generation

### William

### Brady

### Manasi

### Rachael
